
import __ASTRO_IMAGE_IMPORT_ZY1qqR from "../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Falfajores.yaml";
import __ASTRO_IMAGE_IMPORT_Z1lBATC from "../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fbudines.yaml";
import __ASTRO_IMAGE_IMPORT_Z2w8TOj from "../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fregalos.yaml";
import __ASTRO_IMAGE_IMPORT_ZPAYwR from "../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fpostres.yaml";
import __ASTRO_IMAGE_IMPORT_15Mz0j from "../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Ftortas.yaml";
import __ASTRO_IMAGE_IMPORT_2AEwa from "../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Falfajor-maicena.yaml";
import __ASTRO_IMAGE_IMPORT_Z1O4QHA from "../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Falfajor-chocolate.yaml";
import __ASTRO_IMAGE_IMPORT_ZdwI9w from "../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fbudin-marmolado.yaml";
import __ASTRO_IMAGE_IMPORT_2uPp7w from "../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fbudin-limon.yaml";
import __ASTRO_IMAGE_IMPORT_Z7F3cg from "../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fflan-caramelo.yaml";
import __ASTRO_IMAGE_IMPORT_ZPrszn from "../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fcombohoy-mate.yaml";
import __ASTRO_IMAGE_IMPORT_Z23J2hc from "../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fcaja-sorpresa.yaml";
import __ASTRO_IMAGE_IMPORT_Z1JAS1K from "../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftiramisu.yaml";
import __ASTRO_IMAGE_IMPORT_LDYvw from "../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-chocolate.yaml";
import __ASTRO_IMAGE_IMPORT_Z1CE34v from "../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-frutal.yaml";
import __ASTRO_IMAGE_IMPORT_ZQld4G from "../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-personalizada.yaml";
export default new Map([["../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Falfajores.yaml", __ASTRO_IMAGE_IMPORT_ZY1qqR], ["../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fbudines.yaml", __ASTRO_IMAGE_IMPORT_Z1lBATC], ["../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fregalos.yaml", __ASTRO_IMAGE_IMPORT_Z2w8TOj], ["../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Fpostres.yaml", __ASTRO_IMAGE_IMPORT_ZPAYwR], ["../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fcategory%2Ftortas.yaml", __ASTRO_IMAGE_IMPORT_15Mz0j], ["../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Falfajor-maicena.yaml", __ASTRO_IMAGE_IMPORT_2AEwa], ["../../assets/images/img_alfajores.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Falfajor-chocolate.yaml", __ASTRO_IMAGE_IMPORT_Z1O4QHA], ["../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fbudin-marmolado.yaml", __ASTRO_IMAGE_IMPORT_ZdwI9w], ["../../assets/images/img_budines.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fbudin-limon.yaml", __ASTRO_IMAGE_IMPORT_2uPp7w], ["../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fflan-caramelo.yaml", __ASTRO_IMAGE_IMPORT_Z7F3cg], ["../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fcombohoy-mate.yaml", __ASTRO_IMAGE_IMPORT_ZPrszn], ["../../assets/images/img_regalos.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Fcaja-sorpresa.yaml", __ASTRO_IMAGE_IMPORT_Z23J2hc], ["../../assets/images/img_postres.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftiramisu.yaml", __ASTRO_IMAGE_IMPORT_Z1JAS1K], ["../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-chocolate.yaml", __ASTRO_IMAGE_IMPORT_LDYvw], ["../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-frutal.yaml", __ASTRO_IMAGE_IMPORT_Z1CE34v], ["../../assets/images/img_tortas.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproduct%2Ftorta-personalizada.yaml", __ASTRO_IMAGE_IMPORT_ZQld4G]]);
		